/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and list books */
        get: operations["searchBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a book by ID */
        get: operations["getBookById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get weighted category breakdown for a book */
        get: operations["getBookCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{bookId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews for a book */
        get: operations["getBookReviews"];
        put?: never;
        /** Create a review for a book */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{bookId}/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a review */
        put: operations["updateReview"];
        post?: never;
        /** Delete a review */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category by ID */
        get: operations["getCategoryById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile */
        get: operations["getCurrentUser"];
        put?: never;
        /** Register profile on first login */
        post: operations["registerCurrentUser"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated user profile */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/users/me/shelves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user shelves */
        get: operations["getCurrentUserShelves"];
        put?: never;
        /** Create a custom shelf for the authenticated user */
        post: operations["createShelf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/shelves/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder the authenticated user's shelves */
        put: operations["reorderShelves"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/shelves/{shelfId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom shelf and all its book-state entries */
        delete: operations["deleteShelf"];
        options?: never;
        head?: never;
        /** Rename or toggle privacy of a custom shelf */
        patch: operations["updateShelf"];
        trace?: never;
    };
    "/users/me/shelves/{shelfId}/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List books on a shelf */
        get: operations["getShelfBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/books/{bookId}/read-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record that the authenticated user finished reading a book */
        post: operations["logBookRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/read-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's read-log entries */
        get: operations["getReadLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated reading statistics for the authenticated user */
        get: operations["getUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/books/{bookId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add or move a book to a shelf */
        put: operations["setBookState"];
        post?: never;
        /** Remove a book from all shelves */
        delete: operations["removeBookState"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's own suggestions */
        get: operations["getMySuggestions"];
        put?: never;
        /** Submit a suggestion */
        post: operations["submitSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List suggestions pending moderation */
        get: operations["adminListSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/suggestions/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Approve or reject a suggestion */
        put: operations["adminDecideSuggestion"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example 404 */
            status: number;
            /** @example RESOURCE_NOT_FOUND */
            code: string;
            /** @example Book with id 'abc' was not found. */
            message: string;
            /** @example /bookrithm/v1/books/abc */
            path?: string;
            /** Format: date-time */
            timestamp: string;
        };
        PageMeta: {
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        /** @enum {string} */
        BookSource: "GOOGLE_BOOKS";
        /** @enum {string} */
        BookSortBy: "READS" | "SHELVED";
        /** @enum {string} */
        MaturityRating: "UNKNOWN" | "EVERYONE" | "TEEN" | "MATURE";
        /** @enum {string} */
        SuggestionStatus: "PENDING" | "APPROVED" | "REJECTED";
        /** @enum {string} */
        SuggestionType: "CATEGORY" | "TROPE" | "CONTENT_WARNING";
        /** @enum {string} */
        TrustLevel: "NORMAL" | "TRUSTED" | "MODERATOR" | "ADMIN";
        /** @enum {string} */
        ReaderStatus: "READING" | "COZY_READING" | "BETWEEN_BOOKS" | "SEARCHING" | "REREADING" | "ON_HIATUS" | "BUSY";
        CategoryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parentId?: string | null;
            maturity: components["schemas"]["MaturityRating"];
        };
        CategoryWeightResponse: {
            category: components["schemas"]["CategoryResponse"];
            weight: number;
            /** Format: date-time */
            computedAt: string;
        };
        CategoryPage: {
            content: components["schemas"]["CategoryResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        BookResponse: {
            /** Format: uuid */
            id: string;
            source: components["schemas"]["BookSource"];
            title: string;
            author: string;
            description?: string | null;
            coverUrl?: string | null;
            isFanfiction: boolean;
            maturity: components["schemas"]["MaturityRating"];
            isbn10?: string | null;
            isbn13?: string | null;
        };
        BookPage: {
            content: components["schemas"]["BookResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            avatarUrl?: string | null;
            bio?: string | null;
            readerStatus?: components["schemas"]["ReaderStatus"];
            isPrivate: boolean;
            /** @description Only returned when isPrivate is false or the requester is the owner. */
            firstName?: string | null;
            /** @description Only returned when isPrivate is false or the requester is the owner. */
            lastName?: string | null;
            /** @description Only returned when isPrivate is false or the requester is the owner. */
            location?: string | null;
            websiteUrl?: string | null;
            goodreadsUrl?: string | null;
            storyGraphUrl?: string | null;
            instagramUrl?: string | null;
            twitterUrl?: string | null;
            allowAnonymousPublicReviews?: boolean;
            allowPublicCredibilityStats?: boolean;
            trustLevel: components["schemas"]["TrustLevel"];
            /** Format: date-time */
            createdAt: string;
        };
        RegisterUserRequest: {
            username: string;
            displayName: string;
            /** Format: email */
            email: string;
        };
        UpdateUserRequest: {
            username?: string;
            displayName?: string;
            firstName?: string | null;
            lastName?: string | null;
            location?: string | null;
            bio?: string | null;
            avatarUrl?: string | null;
            websiteUrl?: string | null;
            goodreadsUrl?: string | null;
            storyGraphUrl?: string | null;
            instagramUrl?: string | null;
            twitterUrl?: string | null;
            readerStatus?: components["schemas"]["ReaderStatus"];
            isPrivate?: boolean;
            allowAnonymousPublicReviews?: boolean;
            allowPublicCredibilityStats?: boolean;
        };
        ShelfResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isSystem: boolean;
            isPrivate: boolean;
            maxItems?: number | null;
            bookCount: number;
            displayOrder: number;
        };
        SetBookStateRequest: {
            /** Format: uuid */
            shelfId: string;
        };
        UserBookStateResponse: {
            /** Format: uuid */
            bookId: string;
            bookTitle?: string | null;
            /** Format: uuid */
            shelfId: string;
            shelfName: string;
            position: number;
            /** Format: date-time */
            addedAt: string;
            readCount: number;
        };
        UserBookStatePage: {
            content: components["schemas"]["UserBookStateResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        ReviewRequest: {
            /**
             * @description When true, the reviewer's identity is hidden from other users.
             * @default false
             */
            isAnonymous: boolean;
            overall?: number;
            grammar?: number;
            storytelling?: number;
            worldbuilding?: number;
            characters?: number;
            pacing?: number;
            reviewText?: string;
        };
        ReviewResponse: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Present when the requester is the review owner or the review is not anonymous. Null when isAnonymous is true and the requester is not the review owner — the backend must redact this field rather than returning the real userId.
             */
            userId?: string | null;
            /** Format: uuid */
            bookId: string;
            /** @description When true, the reviewer's identity should not be displayed. */
            isAnonymous: boolean;
            overall?: number | null;
            grammar?: number | null;
            storytelling?: number | null;
            worldbuilding?: number | null;
            characters?: number | null;
            pacing?: number | null;
            reviewText?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ReviewPage: {
            content: components["schemas"]["ReviewResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        SuggestionRequest: {
            type: components["schemas"]["SuggestionType"];
            /** Format: uuid */
            bookId?: string | null;
            payload: {
                [key: string]: unknown;
            };
        };
        /** @description Minimal book reference embedded in other responses (e.g. suggestions). */
        BookSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            coverUrl?: string | null;
        };
        SuggestionResponse: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["SuggestionType"];
            status: components["schemas"]["SuggestionStatus"];
            payload?: {
                [key: string]: unknown;
            };
            /** @description The book this suggestion is linked to, if any. */
            book?: components["schemas"]["BookSummary"];
            aiConfidence?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            decidedAt?: string | null;
        };
        SuggestionPage: {
            content: components["schemas"]["SuggestionResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        SuggestionDecisionRequest: {
            approved: boolean;
            reason?: string;
        };
        CreateShelfRequest: {
            name: string;
        };
        UpdateShelfRequest: {
            name?: string | null;
            isPrivate?: boolean;
        };
        ReorderShelvesRequest: {
            shelfIds: string[];
        };
        ReadLogEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bookId: string;
            bookTitle?: string | null;
            /** Format: date-time */
            completedAt: string;
        };
        ReadLogPage: {
            content: components["schemas"]["ReadLogEntry"][];
            page: components["schemas"]["PageMeta"];
        };
        CategoryReadCount: {
            category: components["schemas"]["CategoryResponse"];
            readCount: number;
        };
        UserReadStats: {
            /** Format: int64 */
            totalReads: number;
            /** Format: int64 */
            uniqueBooksRead: number;
            topCategories: components["schemas"]["CategoryReadCount"][];
        };
    };
    responses: {
        /** @description Invalid request body or query parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid authentication token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated user lacks the required role or permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdPathParam: string;
        BookIdPathParam: string;
        ReviewIdPathParam: string;
        ShelfIdPathParam: string;
        PageParam: number;
        SizeParam: number;
        XRequestId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Echoed request correlation ID. */
        XRequestIdResponse: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchBooks: {
        parameters: {
            query?: {
                q?: string;
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
                maturity?: components["schemas"]["MaturityRating"];
                categoryId?: string;
                sortBy?: components["schemas"]["BookSortBy"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of books */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getBookById: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getBookCategories: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Weighted category list for the book */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryWeightResponse"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getBookReviews: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                bookId: components["parameters"]["BookIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPage"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                bookId: components["parameters"]["BookIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Review created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateReview: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                bookId: components["parameters"]["BookIdPathParam"];
                reviewId: components["parameters"]["ReviewIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Review updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                bookId: components["parameters"]["BookIdPathParam"];
                reviewId: components["parameters"]["ReviewIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                parentId?: string;
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPage"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getCategoryById: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    registerCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            /** @description User profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCurrentUserShelves: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of shelves */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createShelf: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShelfRequest"];
            };
        };
        responses: {
            /** @description Shelf created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reorderShelves: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderShelvesRequest"];
            };
        };
        responses: {
            /** @description Shelves reordered and returned in new display order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfResponse"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteShelf: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                shelfId: components["parameters"]["ShelfIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shelf deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateShelf: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                shelfId: components["parameters"]["ShelfIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShelfRequest"];
            };
        };
        responses: {
            /** @description Shelf updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getShelfBooks: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                shelfId: components["parameters"]["ShelfIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of books on the shelf */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBookStatePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logBookRead: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                bookId: components["parameters"]["BookIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read log entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadLogEntry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getReadLog: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated read-log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadLogPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserStats: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reading statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReadStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    setBookState: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                bookId: components["parameters"]["BookIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBookStateRequest"];
            };
        };
        responses: {
            /** @description Book state updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBookStateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    removeBookState: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                bookId: components["parameters"]["BookIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book removed from shelf */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMySuggestions: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of the current user's suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    submitSuggestion: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionRequest"];
            };
        };
        responses: {
            /** @description Suggestion accepted and queued for AI review */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminListSuggestions: {
        parameters: {
            query?: {
                status?: components["schemas"]["SuggestionStatus"];
                type?: components["schemas"]["SuggestionType"];
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminDecideSuggestion: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionDecisionRequest"];
            };
        };
        responses: {
            /** @description Decision recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
